server:
  port: 8081
  
#datasource configuration  
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres?createDatabaseIfNotExist=true
    username: postgres
    password: Presu@12
    driver-class-name: org.postgresql.Driver
   
  # jpa configuration 
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
    show-sql: true
  
  application:
    name: employee-user-service
   
# dailect spring boot can auto detects, but we can set here also
    
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    
    
      

    